version: 2
jobs:
  dependency_cache:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  node-v10-latest:
    docker:
      - image: rollupcabal/circleci-node-v10:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Rebuild
          command: npm install
      - run:
          name: Run unit tests.
          command: npm run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Rebuild
          command: npm install
      - run:
          name: Run linting.
          command: npm run lint
      - run:
          name: Run Security Check
          command: npm run security
      - run:
          name: Validate Commit Messages
          command: npm run ci:lint:commits
workflows:
  version: 2
  validate:
    jobs:
      - dependency_cache
      - analysis:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node-v10-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
